name: default

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: |
          helm lint ./charts/otfd
          helm lint ./charts/otf-agent
      - name: Render
        run: |
          helm template ./charts/otfd
          helm template ./charts/otf-agent --set token=my_agent_token --set url=https://otf.ninja
      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
      - name: Test
        run: |
          make test-otfd
      - name: Debug
        if: failure()
        run: |
          kubectl -n otfd-test get all
          kubectl -n otfd-test describe pod
          kubectl -n otfd-test logs -l app.kubernetes.io/name=postgresql
          kubectl -n otfd-test logs -l app.kubernetes.io/name=otfd
  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: lint-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
