name: default

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Lint
        run: helm lint ./charts/otf

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0

      - name: Test
        run: |
          helm install -f ./charts/otf/test-values.yaml otf ./charts/otf --wait
          helm test otf

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: lint-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
